# Generated by Django 4.0.4 on 2022-04-21 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=200, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('male', models.BooleanField(default=False)),
                ('female', models.BooleanField(default=False)),
            ],
        ),
    ]
