# Generated by Django 4.0.4 on 2022-04-21 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
