# Generated by Django 4.0.4 on 2022-04-21 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div_name', models.CharField(max_length=150, null=True)),
                ('div_code', models.CharField(max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.IntegerField(max_length=11, null=True)),
                ('name', models.CharField(max_length=150, null=True)),
                ('address', models.TextField(max_length=200, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('male', models.BooleanField(default=False)),
                ('female', models.BooleanField(default=False)),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CMS.division')),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_title', models.CharField(max_length=200, null=True)),
                ('exp_education', models.CharField(max_length=200, null=True)),
                ('exp_graduate', models.DateField()),
                ('exp_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CMS.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=150, null=True)),
                ('grade_code', models.CharField(max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SKA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ska_name', models.CharField(max_length=200, null=True)),
                ('publisher', models.CharField(max_length=200, null=True)),
                ('publish_date', models.DateField()),
                ('expire_date', models.DateField()),
                ('exp_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CMS.expert')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, null=True)),
                ('project_file', models.FileField(upload_to='')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('bast_date', models.DateField()),
                ('bast_value', models.IntegerField(max_length=3, null=True)),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CMS.division')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CMS.grade'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
