# Generated by Django 4.0.4 on 2022-04-21 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0002_alter_employee_nip_alter_project_bast_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CMS.expert')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CMS.project')),
            ],
        ),
    ]
