# Generated by Django 4.0.4 on 2022-05-27 04:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0005_employee_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='bast_value',
            field=models.CharField(max_length=3, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
